# Generated by Django 4.1.5 on 2024-02-14 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_certificate_of_good_conduct_studentprofile_certificate_ent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='certificate_ent',
        ),
    ]
