# Generated by Django 4.1.5 on 2024-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_passport',
            field=models.FileField(max_length=256, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='school_documents',
            field=models.FileField(max_length=256, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_certificate',
            field=models.FileField(max_length=256, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_photo',
            field=models.FileField(max_length=256, upload_to=''),
        ),
    ]
