# Generated by Django 4.1.5 on 2024-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_document_document_passport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_passport',
            field=models.FileField(max_length=256, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='school_documents',
            field=models.FileField(max_length=256, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_certificate',
            field=models.FileField(max_length=256, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_photo',
            field=models.FileField(max_length=256, upload_to='uploads/'),
        ),
    ]
