# Generated by Django 5.0.2 on 2024-02-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_document_document_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_photo',
            field=models.ImageField(max_length=256, upload_to='uploads/'),
        ),
    ]
