# Generated by Django 5.0.2 on 2024-02-27 16:35

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_studentprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_passport',
            field=models.FileField(max_length=256, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'pdf']), accounts.models.validate_file_maintype]),
        ),
        migrations.AlterField(
            model_name='document',
            name='school_documents',
            field=models.FileField(max_length=256, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'pdf']), accounts.models.validate_file_maintype]),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_certificate',
            field=models.FileField(max_length=256, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'pdf']), accounts.models.validate_file_maintype]),
        ),
    ]
